### ISSUE TITLE
Add Facebook page

### ISSUE THREAD

**Issue by milandv** [p3lab/GetSocialMediaHandles#1]
Should we add a function to find the Facebook page? Since most people looking for one might also reasonably be looking for the other at the same time?

**Comment by jaeyk** [comment]
We should. But it's also related to API issue (esp availability) ... let's discuss this next in the next meeting.

**Comment by milandv** [comment]
Yup. For sure. (I guess I was thinking about researchers who might want to access them non-programatically for now though I'm also still hoping to make progress on getting Facebook to change their policy.)

But, yes. Let's talk about it and then decide what to do. Good plan.

**Comment by jaeyk** [comment]
Not a top priority for now.

**Comment by milandv** [comment]
Haven't actually created the code yet but i think the core change is this:

```
        filter(grepl("facebook.com/", href) &
                   !grepl("/sharer/", href) & # not the org fb page but a link to share the url
                   !grepl("/posts/", href) & # not the org fb page but a post they shared
                   !grepl("facebook.com/wix", href)) %>% # This is the Wix website dev default 
```

Putting it here for when I or someone gets there.

**Comment by jaeyk** [comment]
@milandv We can create a test version code (maybe using another branch).
